### ISSUE TITLE
Bug where groupchat and local chat double

### ISSUE THREAD

**Issue by redmag3** [DevotedMC/NameLayer#12]
I'm getting a strange bug where groupchats and local chats are duplicated, so that when you try to use groupchat you also get a local chat ... it's odd.

**Comment by ProgrammerDan** [comment]
Why would this be a namelayer issue? Do you have any other details?

Probably, open an issue over on CivChat2 repository -- and provide details there including namelayer version, civchat version, etc.

**Comment by redmag3** [comment]
actually I tested it more, looks like a civchat2 issue, I'll post over there
