### ISSUE TITLE
Error using namelayer

### ISSUE THREAD

**Issue by pvprangergod** [DevotedMC/NameLayer#28]
Hi
I am trying to using namelayer on my 1.10.2 spigot server
With namelayer 1.12 and 1.10.2 I get the same error and don't know how to fix it
https://pastebin.com/7cZzZ8Kw
I don't use sql and I'm running my server from my local pc.
Any help is appreciated, thanks.

**Comment by ProgrammerDan** [comment]
Hello friend, it looks like you haven't set up a database. Namelayer doesn't function without one. 

I recommend, for full compatibility, using MariaDB 10.2 or newer. It's an easy install for prettymuch any OS: https://mariadb.com/kb/en/mariadb/binary-packages/
