### ISSUE TITLE
Numbering bug with /nllg

### ISSUE THREAD

**Issue by soerxpso** [DevotedMC/NameLayer#7]
When I run "/nllg [n]" (where [n] is a number), the part at the top of the output that should say "Page [n] / [total pages]" (assuming n is less than total pages, otherwise it should say "Page [total pages] / [total pages]") instead outputs "Page [n + 1] / [n]". The correct page is shown, but the numbering at the top is always off. Here are some screenshots to better display what I'm talking about:

The result of "/nllg": https://i.gyazo.com/c640d6089b401f12c642925857cdb022.png
The result of "/nllg 2": https://i.gyazo.com/7051a59d3b245d0a0699d940c1cb5d9a.png
The result of "nllg 5": https://i.gyazo.com/11538c9b99ea5afc131218cb4dfbfbf9.png
The result of "/nllg [anything higher than 5]": https://i.gyazo.com/620dfa2888b51cfc81ee083d2c9967b8.png

I am not sure if this bug occurs for other players. It doesn't seem that there's any problem with the functionality, it's just annoying to see the wrong numbers.

**Comment by ProgrammerDan** [comment]
I'm in the process of updating us to the latest namelayer, where this and
other bugs have been fixed.
