### ISSUE TITLE
Subgroups sometimes unlink themselves

### ISSUE THREAD

**Issue by soerxpso** [DevotedMC/NameLayer#8]
I'm not 100% sure how to reproduce this, or really what's happening, so I'll explain it in the form of a narrative:

I was messing with group hierarchies, and I had a main group called Bespin. Under Bespin, I had a whole slew of subgroups. Some of those subgroups had their own subgroups. After a lot of messing with stuff (adding/removing subgroups of Bespin, adding/removing permissions, adding/removing members), a group called BespinCenter, which was a subgroup of Bespin, freaked out and unlinked itself from everything. I don't think I was directly messing with BespinCenter when that happened, but I was messing with other subgroups of Bespin. I fixed the issue by just relinking BespinCenter's subgroups, then relinking BespinCenter to Bespin, HOWEVER, this created a duplicate on the /nllsg output of Bespin (BespinCenter is listed twice). A bit later, the same thing happened again, and I fixed it the same way, and it duplicated itself again on the list. Here is a screenshot: https://i.gyazo.com/2580113b7bcaeec3eddc9920ea172076.png As you can see, BespinCenter is listed three times, but only one of those listings lists BespinCenter's subgroups alongside it.

**Comment by soerxpso** [comment]
After causing the problem again somehow, I'm fairly certain that it happens when you modify the permissions (/nlmp) of a third-layer subgroup.

**Comment by ShadedJon** [comment]
@maxopoly

**Comment by Maxopoly** [comment]
No clue, since you are running a 3 month older version. Since then the way inheritation works was completly reworked, because of issues like this. I doubt this would still occur on the latest version.

**Comment by ProgrammerDan** [comment]
Yeah, I guess I commented to that effect somewhere else. I'm not going to bother with this issue unless it can be reproduced once I'm done merging in Civcraft's latest.
